model_list:
  - model_name: bedrock-claude-haiku
    litellm_params:
      model: bedrock/us.anthropic.claude-haiku-4-5-20251001-v1:0
      aws_region_name: os.environ/AWS_REGION_NAME

general_settings:
  master_key: os.environ/LITELLM_MASTER_KEY

litellm_settings:
  callbacks:
    - prometheus
    - datadog
  service_callback:
    - datadog
  require_auth_for_metrics_endpoint: false
